In [1]:
#importing libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

# Loading data
dataset= load_dataset('lukebarousse/data_jobs')
df= dataset['train'].to_pandas()

#Data cleanup
df['job_posted_date']= pd.to_datetime(df['job_posted_date'])

'[Errno 11001] getaddrinfo failed' thrown while requesting HEAD https://huggingface.co/datasets/lukebarousse/data_jobs/resolve/ed776e5a0a8c40ea9d5efbd800772ae52e140f3e/data_jobs.py
Retrying in 1s [Retry 1/5].
Using the latest cached version of the dataset since lukebarousse/data_jobs couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at C:\Users\Ezekiel\.cache\huggingface\datasets\lukebarousse___data_jobs\default\0.0.0\ed776e5a0a8c40ea9d5efbd800772ae52e140f3e (last modified on Thu Apr  2 10:40:05 2026).

In [ ]:
df_salary= df[pd.notna(df['salary_year_avg'])].copy()

def projected_salary( salary):
    return print(f" your salary is {salary} your projected salary is: {salary * 1.03}" )


df_salary['salary_year_avg'].apply(projected_salary)

In [ ]:
import ast
def clean_up(skill):
    if pd.notna(skill):
        return ast.literal_eval(skill)


df['job_skills']= df['job_skills'].apply(clean_up)


df['job_skills'][0:5]

0                                                 None
1           [r, python, sql, nosql, power bi, tableau]
2    [python, sql, c#, azure, airflow, dax, docker,...
3    [python, c++, java, matlab, aws, tensorflow, k...
4    [bash, python, oracle, aws, ansible, puppet, j...
Name: job_skills, dtype: object

In [43]:
def new_salary(row):
    if "Senior" in row["job_title_short"]:
        return 1.05* row['salary_year_avg']
    else:
        return 1.03*row['salary_year_avg']


df_salary['inflated_salary']= df_salary.apply(new_salary, axis= 1)

df_salary[['job_title_short', 'salary_year_avg', 'inflated_salary']]

       job_title_short  salary_year_avg  inflated_salary
28      Data Scientist         109500.0        112785.00
77       Data Engineer         140000.0        144200.00
92       Data Engineer         120000.0        123600.00
100     Data Scientist         228222.0        235068.66
109       Data Analyst          89000.0         91670.00
...                ...              ...              ...
785624   Data Engineer         139216.0        143392.48
785641   Data Engineer         150000.0        154500.00
785648  Data Scientist         221875.0        228531.25
785682  Data Scientist         157500.0        162225.00
785692  Data Scientist         157500.0        162225.00

[22003 rows x 3 columns]

In [41]:
df['inflated_salary'] = new_salary(df_salary)

df_salary[['job_title_short', 'salary_year_avg', 'inflated_salary']]

       job_title_short  salary_year_avg  inflated_salary
28      Data Scientist         109500.0        112785.00
77       Data Engineer         140000.0        144200.00
92       Data Engineer         120000.0        123600.00
100     Data Scientist         228222.0        235068.66
109       Data Analyst          89000.0         91670.00
...                ...              ...              ...
785624   Data Engineer         139216.0        143392.48
785641   Data Engineer         150000.0        154500.00
785648  Data Scientist         221875.0        228531.25
785682  Data Scientist         157500.0        162225.00
785692  Data Scientist         157500.0        162225.00

[22003 rows x 3 columns]